[[protocols]]
name = "custom-rds"
protocol = "nec"
variant = "necx"
[protocols.scancodes]
#0x70702 = "KEY_POWER"
0x70704 = "KEY_1"
0x70705 = "KEY_2"
0x70706 = "KEY_3"
0x70708 = "KEY_4"
0x70709 = "KEY_5"
0x7070a = "KEY_6"
0x7070c = "KEY_7"
0x7070d = "KEY_8"
0x7070e = "KEY_9"
0x70711 = "KEY_0"
0x70701 = "KEY_SWITCHVIDEOMODE"
0x70707 = "KEY_VOLUMEUP"
0x7070b = "KEY_VOLUMEDOWN"
0x70713 = "KEY_BACK"
0x7070f = "KEY_MUTE"
0x70712 = "KEY_CHANNELUP"
0x70710 = "KEY_CHANNELDOWN"
0x7071a = "KEY_MENU"
0x7074f = "KEY_EPG"
0x7073e = "KEY_ZOOM"
0x70768 = "KEY_OK"
0x70760 = "KEY_UP"
0x70765 = "KEY_LEFT"
0x70762 = "KEY_RIGHT"
0x70761 = "KEY_DOWN"
0x7071f = "KEY_INFO"
0x7076c = "KEY_RED"
0x70714 = "KEY_GREEN"
0x70715 = "KEY_YELLOW"
0x70716 = "KEY_BLUE"
0x70784 = "KEY_REWIND"
0x707eb = "KEY_PLAY"
0x7078b = "KEY_PAUSE"
#0x7078b = "KEY_FORWARD"
0x7072c = "KEY_PREVIOUS"
0x70758 = "KEY_STOP"
0x7074b = "KEY_RECORD"
0x7071b = "KEY_NEXT"
